version: "3"

services:
  db:
    image: postgres:10.10
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  phppgadmin:
    restart: always
    image: dockage/phppgadmin:latest
    ports:
    - "8880:80"
    environment:
    - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
    - PHP_PG_ADMIN_SERVER_HOST=db
    - PHP_PG_ADMIN_SERVER_PORT=5432
    - PHP_PG_ADMIN_SERVER_SSL_MODE=allow
    - PHP_PG_ADMIN_SERVER_DEFAULT_DB=postgres
